//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;

//namespace SolidEdgeCommunity.Extensions
//{
//    /// <summary>
//    /// SolidEdgeDraft.DrawingView extension methods.
//    /// </summary>
//    public static class DrawingViewExtensions
//    {
//        /// <summary>
//        /// Returns the origin of the drawing view.
//        /// </summary>
//        public static System.Windows.Point GetOrigin(this SolidEdgeDraft.DrawingView drawingView)
//        {
//            var x = 0.0;
//            var y = 0.0;
//            drawingView.GetOrigin(out x, out y);
//            return new System.Windows.Point(x, y);
//        }
//    }
//}
